### ISSUE TITLE
Add Sieve of Eratosthenes With Linear Time Complexity

### ISSUE THREAD

**Issue by decon-harsh** [decon-harsh/Competitive-Programming#5]

**Comment by DoC-CoddER** [comment]
Pleased assign

**Comment by SynTax19** [comment]
Hello @decon-harsh Please assign me this task .

**Comment by decon-harsh** [comment]
Yours @Syntax0002

**Comment by nishant-giri** [comment]
@decon-harsh, kindly assign me this task.

**Comment by nishant-giri** [comment]
@decon-harsh, I've added code for Sieve of Eratosthenes algorithm in #33.
