### ISSUE TITLE
Add National Dutch Flag Algo

### ISSUE THREAD

**Issue by decon-harsh** [decon-harsh/Competitive-Programming#8]
Three part sorting is done using Dutch National Flag Algorithm, Explain with comments and write code for it

**Comment by DoC-CoddER** [comment]
Pleased assign

**Comment by asteriskesky** [comment]
hey, I'd love to take this up

**Comment by decon-harsh** [comment]
Yours @asteriskUI

**Comment by decon-harsh** [comment]
@DoC-CoddER Multiple assignment
